#!/bin/sh

export POSTGRESQL_VERSION=9.3.1
export POSTGRESQL_NAME=postgresql
export POSTGRESQL_ARCHIVE=$POSTGRESQL_NAME-POSTGRESQL_VERSION.tar.gz
export POSTGRESQL_URL=http://ftp.postgresql.org/pub/source/v$POSTGRESQL_VERSION/$POSTGRESQL_ARCHIVE

curl -o $POSTGRESQL_ARCHIVE $POSTGRESQL_URL
tar xvf $POSTGRESQL_ARCHIVE

